### PR TITLE
migrate v15.5.x

### PR DESCRIPTION
**Pull request by RedgooseDev**

### CODE REVIEW

**Comment by WickyNilliams** [comment]
😝

**Comment by WickyNilliams** [comment]
I guess this was supposed to be on a separate fork?

**Comment by RedgooseDev** [comment]
I posted a PR but I did not get any response from you. So much it has been fixed.
Is it better to separate it into a new REPO?

**Comment by WickyNilliams** [comment]
I wasn't sure what the PR was for? There were a lot of commits and no explanation attached to it.

**Comment by RedgooseDev** [comment]
At first I had one commit.
After a long time, I fixed the code and I got a lot of commits and closed PR.

Ignore this PR.

Please refer to d369713 instead.

**Comment by WickyNilliams** [comment]
Thanks, I'll cherry-pick that commit when I next make an update

**Comment by RedgooseDev** [comment]
Thank you for your simple and powerful PICKER.

**Pull request closed without merging**
