### PR TITLE
Alpha channel in color chooser

### PR DESCRIPTION
**Pull request by aom**
Adds new slider to allow alpha channel changes. 

 * Colours can be passed in any format now
 * Component returns a rgb or rgba string instead of a hex
 * Removed dependency to Colr and replaced it with tinycolor2 (https://github.com/bgrins/TinyColor) which can parse almost any string to a colour and handle same conversions than Colr did
 * Updated examples

Should alpha channel be optional?

### CODE REVIEW

**Comment by WickyNilliams** [comment]
Thanks Mika! I'm in Asia at the moment without a laptop so there's no way I can really review and test this right now. I'll review when I'm back (end of month or so?)

**Comment by WickyNilliams** [comment]
And yes I'd say alpha should be optional. Off by default.

**Comment by aom** [comment]
@WickyNilliams alpha channel is now disabled by default and can be turned on optionally with **opacitySlider** option. Also toggles **with-opacity-slide** class for ColorPicker-element to allow custom styling of picker as used in example.

**Comment by aom** [comment]
Thx!

**Pull request merged**
